name: hotel_booking
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_pro: ^0.0.13
  font_awesome_flutter: ^8.4.0
  cupertino_icons: ^0.1.2
  flutter_staggered_grid_view: "^0.2.7"
  flutter_sparkline: ^0.1.0
  flutter_circular_chart: ^0.1.0
  http: ^0.11.3+17
  flutter_spinkit: ^3.1.0
  google_sign_in: ^4.0.1+3
  firebase_auth: ^0.11.1
  firebase_core: ^0.4.0+1
  # video_player: "^0.10.0+2"

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/room.jpeg
    - assets/room1.jpg
    - assets/room2.jpg
    - assets/room3.jpg
    - assets/room4.jpg
    - assets/room5.jpg
    - assets/room6.jpg
    - assets/map.png
    - assets/masters1.jpg
    - assets/masters2.jpg
    - assets/masters3.jpg
    - assets/masters4.jpg
    - assets/mini1.jpg
    - assets/mini2.jpg
    - assets/mini3.jpg
    - assets/queen4.jpg
    - assets/queen1.jpg
    - assets/queen2.jpg
    - assets/queen3.jpg
    - assets/king1.jpg
    - assets/king2.jpg
    - assets/king3.jpg
    - assets/king4.jpg
    - assets/quad1.jpg
    - assets/quad2.jpg
    - assets/quad3.jpg
    - assets/quad4.jpg
    - assets/twins1.jpg
    - assets/food1.jpg
    - assets/food2.jpg
    - assets/food3.jpg
    - assets/food4.jpg
    - assets/food5.jpg
    - assets/food6.jpg
    - assets/food7.jpg
    - assets/food8.jpg
    - assets/food9.jpg
    - assets/food10.jpg
    - assets/car1.jpg
    - assets/car2.jpg
    - assets/car3.jpg
    - assets/car4.jpg
    - assets/car5.jpg
    - assets/car6.jpg
    - assets/car7.jpg
    - assets/car8.jpg
    - assets/car9.jpg
    - assets/car10.jpg
    - assets/car11.jpg
    - assets/sport1.jpg
    - assets/me.JPG
    # - assets/videos/#21BullFlag.mp4
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
